version: "3.9"

services:

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./messenger/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./messenger/data:/mosquitto/data
      - ./messenger/log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    env_file:
      - ./db/influx.env
    ports:
      - "8086:8086"
    volumes:
      - ./db/data:/var/lib/influxdb2
    restart: unless-stopped

  event:
    build: ./event
    container_name: event_service
    depends_on:
      - mqtt
      - influxdb
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    restart: unless-stopped

  client:
    build: ./client
    container_name: react_client
    depends_on:
      - event
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  default:
    name: smart_plants_net
